export const movies = {
    INSERT_MOVIES: 'INSERT_MOVIES',
    DELETE_MOVIES: 'DELETE_MOVIES',
    UPDATE_MOVIES: 'UPDATE_MOVIES',
    READ_MOVIES: 'READ_MOVIES',
    FILTER_MOVIES: 'FILTER_MOVIES',
    READ_MOVIE: 'READ_MOVIE'
}